spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
      username: sa
  session:
    store-type: jdbc
  profiles:
    include: local-real, oauth
    active: local
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
        storage_engine: innodb
  h2:
    console:
      enabled: true
