name: springboot-webservice

# push되면 master 브랜치가 트리거되도록 설정
on:
  push:
    branches:
      - master
  workflow_dispatch: # 수동 실행 가능


jobs:
  build: # 해당 Github Action 스크립트가 작동될 OS 환경
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1 # Github Action이 실행될 OS에 JAVA 설치치        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew # gradle wrapper를 실행할 수 있도록 권한 부여
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build # 권한 부여받고 프로젝트 빌드
        shell: bash

