name: springboot-webservice

# push되면 master 브랜치가 트리거됨
on:
  push:
    branches:
      - master
  workflow_dispatch: # 수동 실행 가능


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      -name: Build with Gradle
        run: ./gradlew clean build
        shell: bash

